name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download SCA Resolver
        run: |
          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzvf ScaResolver-linux64.tar.gz
          rm -rf ScaResolver-linux64.tar.gz  
      - name: Run SCA Resolver Scan
        run: |
          ./ScaResolver offline -r "./cx-results1/.cxsca-results.json" -s . -n testGitHubActions --log-level Debug    
      - name: Install Maven, NPM, ... # Add any necessary package management
        run: |
          sudo apt install maven npm
      #- name: Run SCA Resolver Offline Scan
      #  run: |
      #    ./ScaResolver offline -r ./cx-results1/.cxsca-results.json -s . -h       
      - name: Run Checkmarx AST CLI Scan
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /home/linuxbrew/.linuxbrew/bin/brew install checkmarx/ast-cli/ast-cli
          /home/linuxbrew/.linuxbrew/Cellar/ast-cli/*/bin/cx \
            scan create \
            -s ./cx-results1/ \
            --agent GitHub \
            --branch main \
            --scan-types sca \
            --base-uri https://eu.ast.checkmarx.net \
            --tenant dp_wp_account \
            --project-name KB_GHA_JVL_Resolver \
            --client-id  "KB_Github" \
            --client-secret  xqPamnKUF9HtJHN2NO3f6o7XQdfBj4JR \
            --sca-resolver ./ScaResolver \
            --sca-resolver-params "--log-level Debug" \
            --debug
     
