- name: Checkmarx AST Github Action
  # You may pin to the exact commit or the version.
  # uses: Checkmarx/ast-github-action@e216d56a6535d1921fae7e88d50dd580892ed3ef
  uses: Checkmarx/ast-github-action@2.0.14
  with:
          #Provide the AST portal URL
          base_uri: https://eu.ast.checkmarx.net 
          #Provide the Tenant for AST portal URL
          cx_tenant: dp_wp_account
          #Client ID for AST portal authentication
          cx_client_id: KB_Github
          #Secret key for AST portal authentication
          cx_client_secret: 2c0387f1-2e21-46be-a213-7c193cf32e03
          #Select a Checkmarx Project Name
          project_name: KB_JVL_GHA
          #Branch name
          branch: main
          #GitHub API Token
          github_token: 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
          #Additional parameters for AST scan
          additional_params: #optional, default is 

